@startuml
title "Login phase"

box "Client" #LightBlue
participant ClientModel
participant ClientParser
participant ClientController
end box

box "Server" #Pink
participant ServerController
participant ServerParser
participant UserChecker
end box

'Client-Server connections
ClientModel->ClientParser: ping
ClientParser->ClientController: ping
ClientController->ServerController: ping
ClientController<--ServerController: pong
ClientParser<--ClientController: pong
ClientModel<--ClientParser: pong

ClientController<--ServerController: login
ClientParser<--ClientController: login
ClientModel<--ClientParser: login
ClientController<--ServerController: username request
ClientParser<--ClientController: username request
ClientModel<--ClientParser: username request
ClientModel->ClientParser: username
ClientParser->ClientController: username
ClientController->ServerController: username

ServerController->ServerParser: parse username

'Server-UserChecker connections
ServerParser->UserChecker: check username
UserChecker-->ServerParser: result
ServerParser-->ServerController: result
'alt cases
alt successful case
ClientController<--ServerController: data request
ClientParser<--ClientController: data request
ClientModel<--ClientParser: data request
else unsuccessful case
ClientController<--ServerController: error
ClientParser<--ClientController: error
ClientModel<--ClientParser: error
end

ClientModel->ClientParser: UserData
ClientParser->ClientController: UserData
ClientController->ServerController: UserData

ClientController<--ServerController: success
ClientParser<--ClientController: success
ClientModel<--ClientParser: success



@enduml