@startuml
title "Login phase"

box "Client" #LightBlue
participant Client
end box

box "Server" #Pink
participant ServerController
participant ServerParser
participant UserChecker
end box

'Client-Server connections
Client->ServerController: ping
Client<--ServerController: pong

Client<--ServerController: login
Client<--ServerController: username request
Client->ServerController: username
ServerController->ServerParser: parse username

'Server-UserChecker connections
ServerParser->UserChecker: check username
UserChecker-->ServerParser: result
ServerParser-->ServerController: result
'alt cases
alt successful case
Client<--ServerController: data request
else unsuccessful case
Client<--ServerController: error
end

Client->ServerController: UserData
Client<--ServerController: success
@enduml