@startuml


box "Client" #LightBlue
participant Client
end box

box "Server" #Pink
participant ServerController
participant GameController
participant Game
end box

ServerController <-- GameController: currentPlayer turn
ServerController -->Client: it's your turn
Client->Client: check move
Client-> ServerController: Move
ServerController->GameController: Move
GameController->Game: Move
Game->Game: check move
Game--> GameController: Game Update
GameController-->ServerController: Game Update
ServerController-->Client: Game Update
Client->ServerController: bookshelf points update
ServerController->GameController: bookshelf points update
GameController->GameController: check points





@enduml