@startuml
'https://plantuml.com/sequence-diagram

autonumber

Client -> Server:
Server->Server: nextTurn
alt game is ended
Server->Client: "winners": lista nomi vincitori e punteggi
else is last round
Server->Client: "lastRound"
'poi è come in game phase
else the game is not ended and is not last round
'come in game phase
else
@enduml